service: next-material

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-central-1
  memorySize: 264
  timeout: 15
  environment:
    NODE_ENV: production
    LAMBDA: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

package:
  exclude:
    - .git/**

plugins:
  - serverless-apigw-binary
  - serverless-plugin-warmup

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}
    warmup: true
